[2025-04-26T01:10:02.621+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-26T01:10:02.644+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_processing.is_api_available manual__2025-04-26T01:09:59.579345+00:00 [queued]>
[2025-04-26T01:10:02.657+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_processing.is_api_available manual__2025-04-26T01:09:59.579345+00:00 [queued]>
[2025-04-26T01:10:02.658+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-26T01:10:02.857+0000] {taskinstance.py:2890} INFO - Executing <Task(HttpSensor): is_api_available> on 2025-04-26 01:09:59.579345+00:00
[2025-04-26T01:10:02.867+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2264) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-26T01:10:02.872+0000] {standard_task_runner.py:72} INFO - Started process 2266 to run task
[2025-04-26T01:10:02.871+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2025-04-26T01:09:59.579345+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpqc_605bw']
[2025-04-26T01:10:02.877+0000] {standard_task_runner.py:105} INFO - Job 26: Subtask is_api_available
[2025-04-26T01:10:02.933+0000] {task_command.py:467} INFO - Running <TaskInstance: user_processing.is_api_available manual__2025-04-26T01:09:59.579345+00:00 [running]> on host bb0d27cab5a5
[2025-04-26T01:10:03.017+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='user_processing' AIRFLOW_CTX_TASK_ID='is_api_available' AIRFLOW_CTX_EXECUTION_DATE='2025-04-26T01:09:59.579345+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-26T01:09:59.579345+00:00'
[2025-04-26T01:10:03.019+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-26T01:10:03.034+0000] {baseoperator.py:423} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2025-04-26T01:10:03.035+0000] {http.py:140} INFO - Poking: api/
[2025-04-26T01:10:03.045+0000] {base.py:84} INFO - Retrieving connection 'user_api'
[2025-04-26T01:10:16.636+0000] {base.py:339} INFO - Success criteria met. Exiting.
[2025-04-26T01:10:16.652+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-26T01:10:16.653+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, run_id=manual__2025-04-26T01:09:59.579345+00:00, execution_date=20250426T010959, start_date=20250426T011002, end_date=20250426T011016
[2025-04-26T01:10:16.736+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-26T01:10:16.773+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-26T01:10:16.776+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
