[2025-04-26T01:04:47.060+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-26T01:04:47.084+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_processing.is_api_available manual__2025-04-26T01:04:43.342585+00:00 [queued]>
[2025-04-26T01:04:47.096+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_processing.is_api_available manual__2025-04-26T01:04:43.342585+00:00 [queued]>
[2025-04-26T01:04:47.098+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-26T01:04:47.275+0000] {taskinstance.py:2890} INFO - Executing <Task(HttpSensor): is_api_available> on 2025-04-26 01:04:43.342585+00:00
[2025-04-26T01:04:47.286+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2168) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-26T01:04:47.288+0000] {standard_task_runner.py:72} INFO - Started process 2170 to run task
[2025-04-26T01:04:47.288+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2025-04-26T01:04:43.342585+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmptvtd1i72']
[2025-04-26T01:04:47.291+0000] {standard_task_runner.py:105} INFO - Job 18: Subtask is_api_available
[2025-04-26T01:04:47.356+0000] {task_command.py:467} INFO - Running <TaskInstance: user_processing.is_api_available manual__2025-04-26T01:04:43.342585+00:00 [running]> on host bb0d27cab5a5
[2025-04-26T01:04:47.454+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='user_processing' AIRFLOW_CTX_TASK_ID='is_api_available' AIRFLOW_CTX_EXECUTION_DATE='2025-04-26T01:04:43.342585+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-26T01:04:43.342585+00:00'
[2025-04-26T01:04:47.456+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-26T01:04:47.474+0000] {baseoperator.py:423} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2025-04-26T01:04:47.475+0000] {http.py:140} INFO - Poking: api/
[2025-04-26T01:04:47.489+0000] {base.py:84} INFO - Retrieving connection 'user_api'
[2025-04-26T01:04:59.498+0000] {base.py:339} INFO - Success criteria met. Exiting.
[2025-04-26T01:04:59.514+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-26T01:04:59.516+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, run_id=manual__2025-04-26T01:04:43.342585+00:00, execution_date=20250426T010443, start_date=20250426T010447, end_date=20250426T010459
[2025-04-26T01:04:59.559+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-26T01:04:59.594+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-26T01:04:59.598+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
